preprocessing:
  step_name: PreprocessingConfig
  data_path: raw_data
  gen_file: GEN-sarc-notsarc.csv
  hyp_file: HYP-sarc-notsarc.csv
  rq_file: RQ-sarc-notsarc.csv
  preprocessed_file_dir: processed_data
  embedding_model: sentence-transformers/all-mpnet-base-v2
  val_size: 0.1
  test_size: 0.2
  random_state: 77
  batch_size: 30
  processed_data_path: processed_data

schema:
  step_name: schema_validation
  label: str
  text: str
  subClass: str
  possibleSarcClasses: gen, rq, hyp

model-training:
  step_name: model_training
  train_files_path: processed_data
  validation: True
  keep_punctuation_features: True
  num_trials: 3 #15
  models_path: models
  artifacts_dir: artifacts
  confusion_matrix_artifact_file: artifacts/ConfMatrix.txt
  sarc_saved_model_file: sarcClassifier.ubj
  sarc_type_saved_model_file: sarcSubClassClassifier.ubj







